--BRANCH 1 CODES

CREATE TABLE C_INSURANCE
(
  INSURANCE_ID              NUMBER(20),
  SOLID                     VARCHAR2(5 BYTE),
  POLICY_NO                 VARCHAR2(20 BYTE),
  CREATE_DATE               DATE,
  ACCOUNT_NO                VARCHAR2(16 BYTE),
  INSURED_ASSET_DETAILS     VARCHAR2(50 BYTE),
  INSURED_FROM              DATE,
  INSURED_TO                DATE,
  INSURED_AMOUNT            NUMBER(20,2),
  PREMIUM_AMOUNT            NUMBER(20,2),
  INSURANCE_COMPANY         VARCHAR2(50 BYTE),
  BRANCH_NAME               VARCHAR2(50 BYTE),
  CLOSE_DATE                DATE,
  CLOSE_REASON              VARCHAR2(80 BYTE),
  RENEW_DATE                DATE,
  RENEW_INSURANCE_ID        NUMBER(20),
  RECORD_STATUS             NUMBER(2),
  CUSER                     VARCHAR2(50 BYTE),
  CDATE                     DATE,
  MUSER                     VARCHAR2(50 BYTE),
  MDATE                     DATE,
  DUSER                     VARCHAR2(50 BYTE),
  DDATE                     DATE,
  VUSER                     VARCHAR2(50 BYTE),
  VDATE                     DATE,
  CLSUSER                   VARCHAR2(50 BYTE),
  CLSDATE                   DATE,
  RUSER                     VARCHAR2(50 BYTE),
  RDATE                     DATE,
  UUSER                     VARCHAR2(50 BYTE),
  UDATE                     DATE,
  VUUSER                    VARCHAR2(50 BYTE),
  VUDATE                    DATE
);

CREATE INDEX C_INSURANCE_IDX1 ON C_INSURANCE (INSURANCE_ID);
CREATE INDEX C_INSURANCE_IDX2 ON C_INSURANCE (SOLID, CREATE_DATE);
CREATE INDEX C_INSURANCE_IDX3 ON C_INSURANCE (RENEW_INSURANCE_ID);

CREATE PUBLIC SYNONYM C_INSURANCE FOR C_INSURANCE;
GRANT SELECT, INSERT, UPDATE, DELETE ON C_INSURANCE TO TBAGEN,TBACUST,TBAUTIL;

CREATE SEQUENCE C_INSUR_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999999999 CYCLE NOCACHE;

GRANT SELECT ON C_INSUR_SEQ TO TBAGEN,TBACUST,TBAUTIL,TBAADM;
CREATE PUBLIC SYNONYM C_INSUR_SEQ FOR C_INSUR_SEQ;

DELETE FROM C_REFCODE WHERE MAIN_CODE = 1021 AND SUB_CODE = 96 AND CODE_DESCRIPTION = '316';
COMMIT;

INSERT INTO C_REFCODE(MAIN_CODE, SUB_CODE, CODE_DESCRIPTION, DEL_FLAG)
VALUES (1021, 96, '316', 'N');
COMMIT;